name: Emoji Improvement Request
description: Suggest an emoji to be improved, in ways that you see fit.
title: "Emoji Improvement: "
labels: ["enhancement"]
body:
  - type: input
    id: emojiName
    attributes:
      label: Official emoji name
    validations:
      required: true
  - type: input
    id: codepoint
    attributes:
      label: Unicode codepoint
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Link to emoji image
      description: Should be hosted on Scratch Assets or CubeUpload
      placeholder: "https://..."
    validations:
      required: true
  - type: textarea
    id: toBeImproved
    attributes:
      label: "What should be improved about it?"
    validations:
      required: true
